// Generated by CoffeeScript 1.6.3
(function() {
  var Person, p;

  Person = (function() {
    function Person(nickname) {
      var btn,
        _this = this;
      this.nickname = nickname;
      btn = document.getElementById('btn');
      btn.onclick = function() {
        return window.alert("元気かな、" + _this.nickname + "。");
      };
    }

    return Person;

  })();

  p = new Person('やまちゃん');

}).call(this);
