// Generated by CoffeeScript 1.6.3
(function() {
  var Person;

  Person = (function() {
    Person.prototype.status = '健康';

    function Person(name) {
      this.name = name;
    }

    Person.prototype.toString = function() {
      return window.alert("" + this.name + "は" + this.status + "です。");
    };

    return Person;

  })();

  window.Person = Person;

}).call(this);
